### ISSUE TITLE
Name for Gallery

### ISSUE THREAD

**Issue by RickCogley** [eSolia/eSolia#67]
Added gallery function for the detail pages, and a title for it in the data translations files. 

What should the Japanese be? 
- ギャラリー
- 関連画像
- 添付画像
- 画像

**Comment by RickCogley** [comment]
@eishikawa @Hideaki1 @yanquanma @yasuyoshiakiyama  any thoughts? 
This is going to be the title before the gallery photos on each detail page. Need Japanese for it.

**Comment by Hideaki1** [comment]
Translation of Gallery can be ギャラリー, it is pretty much known word.

if it is for title for photos on each details pages, I personally feel no need title in there, but if its need to be, just 画像 is good.

At least, only 添付画像 is not suitable I think.

**Comment by RickCogley** [comment]
@Hideaki1 thanks. 
ギャラリー it is, then.
This is the title of the gallery section on the detail pages.
